services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      #- ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings__DefaultConnection=Server=db;Database=AvengersDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true;Encrypt=False"      
      - "IdentityServer__Key__Type=Production"
    ports:
      - "80:8080"
      #- "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  db:
    ports:
      - "5533:1433"